spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: ${PORT:8080}
